apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bioops-dev

configMapGenerator:
  - name: bioops-config
    envs:
      - runtime.env
  - name: bioops-agents-config
    files:
      - agents.yaml
  - name: bioops-bucket-inventory
    files:
      - bucket_inventory.csv=bucket-inventory.csv

  - name: bioops-infra-mocks
    files:
      - mock_database_health.json
      - mock_queue_metrics.json
      - mock_function_metrics.json

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/part-of: bioops
