apiVersion: v1
kind Secret:
metadata:
  name: bioops-api-secrets
  namespace: bioops-dev
type: Opaque
stringData:
  BITRIX_WEBHOOK_URL: "https://your-domain.bitrix24.ru/rest/YOUR_USER_ID/YOUR_WEBHOOK_CODE"
  BITRIX_DIALOG_ID: "chat14"