apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: bioops-dev
  labels:
    app: qdrant
    app.kubernetes.io/part-of: bioops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
